project:
  type: website
  output-dir: docs

website:
  title: "Chippy Marx"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: Projects.qmd
        text: Projects 
      - href: Resume.qmd
        text: Resume

format:
  html:
    css: styles.scss  
    toc: true



