project:
  type: website
  output-dir: docs

website:
  title: "Chippy Marx"
  favicon: favicon2.jpeg
  navbar:
    title: false
    logo: favicon2.jpeg
    logo-alt: "CSU RAMS"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: Projects.qmd
        text: Projects 
      - href: Resume.qmd
        text: Resume
  page-footer:
    background: light # or 'dark'
    left: "© 2024 Chippy Marx"
    right: "Ecosystem Science and Sustainability and Restoration Ecology"

format:
  html:
    theme: 
    - Lumen
    - styles.scss
    toc: true
    page-layout: full
